### PR TITLE
Use LocalStorage instead of cookies

### PR DESCRIPTION
**Pull request by Sjors**
All browsers that we support, support local storage.

`BrowserHelper.migrateCookiesToLocalStorage()` checks for existing cookies, deletes them and use local storage instead.

### CODE REVIEW

**Comment by Sjors** [comment]
With local storage there's no longer a distinction between `.get()` and `getObject()`. They do however require different treatment in `migrateCookiesToLocalStorage()`.

There were two places where we use `=== 'true'`; the migration changes these to plain old booleans.

@plondon this might be a good opportunity to reorganise the cookies  a bit. If you like, you can tweak `migrateCookiesToLocalStorage()` to rename keys. E.g. I renamed `uid` to `guid`. Surveys could perhaps be grouped under one root key? Same with alerts.

I was a bit confused about the key `contextual-message`.

**Comment by Sjors** [comment]
I resolved the merge conflict.

**Comment by jtormey** [comment]
Do we need `angular-local-storage`? Is the plain browser API not consistent across platforms?

**Comment by Sjors** [comment]
Not sure, but for the same reason I use `$window` and not `window` even the most minimal wrapper is beneficial.

**Comment by Sjors** [comment]
It does seem to do a few things for us, e.g. wrapping objects in JSON: https://github.com/grevory/angular-local-storage/blob/master/src/angular-local-storage.js#L147

**Pull request merged**
