### PR TITLE
Add Indian Rupee

### PR DESCRIPTION
**Pull request by jtormey**
After looking around, I'm pretty sure this is the only frontend change needed to support INR. I added it after HKD, if someone thinks it deserves a different place on the list please let me know.

### CODE REVIEW

**Comment by Sjors** [comment]
Just found your PR when I tried to push my branch. Mine also sets the default currency upon signup, so I took the liberty of force-pushing over you :-P

**Comment by jtormey** [comment]
Needs rebase.

**Comment by Sjors** [comment]
Rebased. Note that this requires backend support to be deployed.

**Comment by Sjors** [comment]
This is good to go, but might need a reabase.

**Pull request closed without merging**
