### PR TITLE
Sign Up disabled on in app browsers

### PR DESCRIPTION
**Pull request by prwelber**
…ign up fields to be disabled

### CODE REVIEW

**Comment by prwelber** [comment]
`info` from the twitter in app browser was `{"browser": null, "version": null, etc...}`. This caused a `typeError` when trying to set `info.browser.toLowerCase()` which resulted in the sign up form being disabled and no error message or warning being shown. The version of twitter I tested which had the disabled sign up screen did pass the `minimumWebkitVersion` test, so this fix should allow users who click through our ads on social to actually sign up.

**Comment by Sjors** [comment]
Other than that the change should be fine.

**Comment by prwelber** [comment]
Thanks! Fixed.

**Comment by Solen-Win** [comment]
Got it. Thanks! 

⁣Sent from BlueMail ​

**Comment by plondon** [comment]
Nice job figuring this one out!

**Comment by Solen-Win** [comment]
Read and edit.

**Pull request merged**
